version: '2.4'

services:

    postgresql_12:
      # jdbc:postgresql://localhost:54333/guest?user=guest&amp;password=guest
      container_name: postgresql_12
      ports:
        - "54333:5432"
      image: postgres:12-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"
